#!/bin/bash

swig -perl5 key_utils.i
gcc -c `perl -MConfig -e 'print join(" ", @Config{qw(ccflags optimize cccdlflags)}, "-I$Config{archlib}/CORE")'` -lssl -lcrypto key_utils.c key_utils_wrap.c
perl Makefile.PL
make
make install

