# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

package key_utils;
use base qw(Exporter);
use base qw(DynaLoader);
package key_utilsc;
bootstrap key_utils;
package key_utils;
@EXPORT = qw();

# ---------- BASE METHODS -------------

package key_utils;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package key_utils;

*generatePem = *key_utilsc::generatePem;
*generateSinFromPem = *key_utilsc::generateSinFromPem;
*getPublicKeyFromPem = *key_utilsc::getPublicKeyFromPem;
*signMessageWithPem = *key_utilsc::signMessageWithPem;
*mysignMessageWithPem = *key_utilsc::mysignMessageWithPem;
*mygeneratePem = *key_utilsc::mygeneratePem;
*mygenerateSinFromPem = *key_utilsc::mygenerateSinFromPem;
*mygetPublicKeyFromPem = *key_utilsc::mygetPublicKeyFromPem;

# ------- VARIABLE STUBS --------

package key_utils;

1;
