# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.5
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

package BitPay::key_utils;
use base qw(Exporter);
use base qw(DynaLoader);
package BitPay::key_utilsc;
bootstrap BitPay::key_utils;
package BitPay::key_utils;
@EXPORT = qw();

# ---------- BASE METHODS -------------

package BitPay::key_utils;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package BitPay::key_utils;

*generatePem = *BitPay::key_utilsc::generatePem;
*generateSinFromPem = *BitPay::key_utilsc::generateSinFromPem;
*getPublicKeyFromPem = *BitPay::key_utilsc::getPublicKeyFromPem;
*signMessageWithPem = *BitPay::key_utilsc::signMessageWithPem;
*mysignMessageWithPem = *BitPay::key_utilsc::mysignMessageWithPem;
*mygeneratePem = *BitPay::key_utilsc::mygeneratePem;
*mygenerateSinFromPem = *BitPay::key_utilsc::mygenerateSinFromPem;
*mygetPublicKeyFromPem = *BitPay::key_utilsc::mygetPublicKeyFromPem;

# ------- VARIABLE STUBS --------

package BitPay::key_utils;

1;
